export const Types = {
  FETCH_DEPARTMENT_SUCCESS: "FETCH_DEPARTMENT_SUCCESS",
  FETCH_DEPARTMENT_REQUEST: "FETCH_DEPARTMENT_REQUEST",
  FETCH_DEPARTMENT_FAILURE: "FETCH_DEPARTMENT_FAILURE",
  UPDATE_SELECTED_DEPARTMENT: "UPDATE_SELECTED_DEPARTMENT",
  STORE_DATA:"STORE_DATA"
};
