export const Types = {
  FETCH_DEPARTMENT_SUCCESS: "FETCH_DEPARTMENT_SUCCESS",
  FETCH_DEPARTMENT_REQUEST: "FETCH_DEPARTMENT_REQUEST",
  FETCH_DEPARTMENT_FAILURE: "FETCH_DEPARTMENT_FAILURE",
  UPDATE_SELECTED_DEPARTMENT: "UPDATE_SELECTED_DEPARTMENT",
  UPDATE_SELECTED_SEMESTER: "UPDATE_SELECTED_SEMESTER"
};
